# Generated by Django 3.2.9 on 2021-12-08 00:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=20)),
                ('grado', models.CharField(choices=[('Primero basico', 'Primero basico'), ('Segundo basico', 'Segundo basico'), ('Tercero basico', 'Tercero basico'), ('Cuarto basico', 'Cuarto basico'), ('Quinto basico', 'Quinto basico'), ('Sexto basico', 'Sexto basico'), ('Septimo basico', 'Septimo basico'), ('Octavo basico', 'Octavo basico'), ('Primero medio', 'Primero medio'), ('Segundo medio', 'Segundo medio'), ('Tercero medio', 'Tercero medio'), ('Cuarto medio', 'Cuarto medio'), ('PDT', 'PDT')], max_length=14)),
                ('asignatura_Basica', models.CharField(choices=[('No', 'No'), ('Matemáticas', 'Matemáticas '), ('Ciencias Naturales', 'Ciencias Naturales'), ('Lenguaje y comunicación', 'Lenguaje y comunicación'), ('Historia, Geografía y Ciencias Sociales', 'Historia, Geografía y Ciencias Sociales'), ('Ingles', 'Ingles'), ('Otros', 'Otros')], default='N', max_length=39)),
                ('asignatura_Media', models.CharField(choices=[('No', 'No'), ('Matemáticas', 'Matemáticas '), ('Matemáticas avanzadas', 'Matemáticas avanzadas'), ('Lenguaje y comunicación', 'Lenguaje y comunicación'), ('Historia, Geografía y Ciencias Sociales', 'Historia, Geografía y Ciencias Sociales'), ('Física', 'Física '), ('Física avanzada', 'Física avanzada'), ('Química', 'Química '), ('Química avanzada', 'Química avanzada'), ('Biología', 'Biología '), ('Biología avanzada', 'Biología avanzada'), ('Inglés', 'Inglés'), ('Otros', 'Otros')], default='No', max_length=39)),
                ('contacto', models.CharField(choices=[('Email', 'Email'), ('instagram', 'instagram'), ('whatsapp', 'whatsapp')], default='Email', max_length=20)),
                ('dato_de_contacto', models.TextField(default='')),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/Fondo.png', upload_to='images/')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
